/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AAvatarGroup: typeof import('ant-design-vue/es')['AvatarGroup']
    AddressCard: typeof import('./src/components/ui/home/AddressCard.vue')['default']
    AgentAppointment: typeof import('./src/components/ui/appointment/AgentAppointment.vue')['default']
    AgentAppointmentList: typeof import('./src/components/ui/appointment/AgentAppointmentList.vue')['default']
    AgentAppointmentListItem: typeof import('./src/components/ui/appointment/AgentAppointmentListItem.vue')['default']
    AgentTable: typeof import('./src/components/ui/agents/AgentTable.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AppointmentAgents: typeof import('./src/components/ui/home/AppointmentAgents.vue')['default']
    AppointmentList: typeof import('./src/components/ui/home/AppointmentList.vue')['default']
    AppointmentListItem: typeof import('./src/components/ui/home/AppointmentListItem.vue')['default']
    AppointmentModal: typeof import('./src/components/ui/modals/AppointmentModal.vue')['default']
    AppointmentPage: typeof import('./src/components/pages/AppointmentPage.vue')['default']
    AppointmentStatus: typeof import('./src/components/ui/home/AppointmentStatus.vue')['default']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Avatar: typeof import('./src/components/ui/common/avatar/Avatar.vue')['default']
    AvatarGroup: typeof import('./src/components/ui/common/filters/AvatarGroup.vue')['default']
    ComboBox: typeof import('./src/components/ui/common/combobox/ComboBox.vue')['default']
    ComboBoxView: typeof import('./src/components/ui/common/combobox/ComboBoxView.vue')['default']
    ContactPage: typeof import('./src/components/pages/ContactPage.vue')['default']
    ContactTable: typeof import('./src/components/ui/contact/ContactTable.vue')['default']
    DashboardPage: typeof import('./src/components/pages/DashboardPage.vue')['default']
    EmptyState: typeof import('./src/components/ui/common/empty/EmptyState.vue')['default']
    FilterSection: typeof import('./src/components/ui/home/FilterSection.vue')['default']
    Loader: typeof import('./src/components/ui/common/loader.vue')['default']
    Navbar: typeof import('./src/components/ui/common/navbar/Navbar.vue')['default']
    RangePicker: typeof import('./src/components/ui/common/filters/RangePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/ui/common/filters/SearchFilter.vue')['default']
    StatusFilter: typeof import('./src/components/ui/common/filters/StatusFilter.vue')['default']
    StatusSection: typeof import('./src/components/ui/home/StatusSection.vue')['default']
    UserCard: typeof import('./src/components/ui/home/UserCard.vue')['default']
    UserSelection: typeof import('./src/components/ui/common/navbar/UserSelection.vue')['default']
  }
}
